### ISSUE TITLE
HttpRedis2Module 密码验证问题

### ISSUE THREAD

**Issue by liaowb1105** [openresty/redis2-nginx-module#26]
redis的连接如果需要密码 ，在哪里设置呢？

**Comment by agentzh** [comment]
@liaowb1105 Please, no Chinese here. If you really want to use Chinese, please join the openresty (Chinese) mailing list instead. Please see http://openresty.org/#Community

Regarding your question, you send the AUTH redis command just as any other redis commands you would send (like GET and SET). See

http://redis.io/commands/AUTH

**Comment by liaowb1105** [comment]
oh,i see.thank you
