### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by lidaohang** [openresty/redis2-nginx-module#28]
您好，章老师，ngx_http_redis_process_header
upstream 读后端redis的数据，怎么才知道读完了没？ 以前http 是一个hander的长度，根据这个长度，来对比知道读了多少~  但是redis协议里面没有这样的~
如果遇到大value， 我怎么判断才能把value读完，然后解析解析处理包装~

**Comment by agentzh** [comment]
@lidaohang Please do not use Chinese here. This place is considered English only. If you really want to use Chinese, please use the openresty (Chinese) mailing list instead. Please see https://openresty.org/#Community for details. Thanks a lot for your cooperation!

Regarding your question, you can use HTTP 1.1 requests to make the nginx server return chunked encoded response bodies. The "last chunk" in the chunked encoding signals the end of the data stream.
