### ISSUE TITLE
Unable to select a database while connecting.

### ISSUE THREAD

**Issue by NicholasMolenaar** [openresty/redis2-nginx-module#31]
All though the usage of databases in Redis seems some what useless. its a really handy feature when hosting multiple websites on the same server to avoid key collision.

Could we add this feature or put it into the documentation if it already exists?

**Comment by maurorappa** [comment]
you can simply run in the same Lua block:

redis2_query select 8;
redis2_query get foo;

This works because the queries are pipelined before using redis2_pass

**Comment by NicholasMolenaar** [comment]
Oké, does this mean i'll also get twice the raw tcp information back?

**Comment by agentzh** [comment]
@NicholasMolenaar Yes. A more flexible and efficient approach is to use ngx_lua with the lua-resty-redis library instead. See

https://github.com/openresty/lua-resty-redis

**Comment by maurorappa** [comment]
Sorry guys,  I don't undestand, I did a tcpodump for the redis_queries above:

09:27:19.310969 IP localhost.46289 > localhost.distinct: Flags [P.], seq 1:47, ack 1, win 512, options [nop,nop,TS val 62266277 ecr 62266277], length 46
        0x0000:  4500 0062 2d3f 4000 4006 0f55 7f00 0001  E..b-?@.@..U....
        0x0010:  7f00 0001 b4d1 270f d273 3699 cb96 9df7  ......'..s6.....
        0x0020:  8018 0200 fe56 0000 0101 080a 03b6 1ba5  .....V..........
        0x0030:  03b6 1ba5 2a32 0d0a 2436 0d0a 7365 6c65  ....*2..$6..sele
        0x0040:  6374 0d0a 2431 0d0a 380d 0a2a 320d 0a24  ct..$1..8..*2..$
        0x0050:  330d 0a67 6574 0d0a 2434 0d0a 696e 666f  3..get..$4..info
        0x0060:  0d0a  

I see both redis command batched in one packet and only once.
Where's the doubling ?

**Comment by agentzh** [comment]
@maurorappa Redis supports command pipelining, which is much more efficient. See

http://redis.io/topics/pipelining
