### ISSUE TITLE
Support for namespace

### ISSUE THREAD

**Issue by vmatekole** [openresty/redis2-nginx-module#33]
Hi!

I am currently using - https://www.nginx.com/resources/wiki/modules/redis/ and am looking to switch over
to openresty flavour. Do is it support namespaces? That was something that was lacking with the current module.

~victor

**Comment by agentzh** [comment]
@vmatekole I'm not aware of the "namespace" thing on the Redis 2.x protocol level. Do you have a link to the corresponding document?

BTW, regarding the openresty flavor of in-nginx redis clients, the state of the art is the lua-resty-redis library based on ngx_lua's cosocket API:

https://github.com/openresty/lua-resty-redis

**Comment by vmatekole** [comment]
@agentzh Apologies for late reply. Upon further investigation namespacing appears to be a practice of prepending keys with a value - enabling multi-tenancy for example. Some clients in Ruby support it natively in that you can define a namespace when connecting to Redis. I don't think namespacing is supported natively within the protocol. Thanks for the tip for the lua-resty-redis - I will take a look :smile:
