### ISSUE TITLE
redis2_pass host:port:db would be nice

### ISSUE THREAD

**Issue by gxbe** [openresty/redis2-nginx-module#34]
is there some reason why this is technically infeasible ?  

It would make it possible to scale using redis "presharding" 

http://oldblog.antirez.com/post/redis-presharding.html

**Comment by agentzh** [comment]
@gxbe It's possible with `redis2_query` and the `select` command I believe. But for the maximum flexibility, use of the `lua-resty-redis` library with the `ngx_lua` module is highly recommended.

**Comment by gxbe** [comment]
hey thanks.

**Comment by jayCorp** [comment]
@gxbe Hey Buddy, stop making me stalk you and go on aim again! :P
