### ISSUE TITLE
nginx不返回数据，而是下载

### ISSUE THREAD

**Issue by lixiaominggit** [openresty/redis2-nginx-module#39]
![image](https://cloud.githubusercontent.com/assets/5425397/16041639/1512c0e4-3269-11e6-8d7f-517d741779e7.png)
我实在找不到原因，希望能帮助我

一直用的redis2-nginx-module,这次新配置的和之前的一样的。但是出现了这个问题：

我访问这个链接的时候nginx返回的是让下载文件，文件的内容是本应该放回的数据。我用的php那些请求是没有问题的

**Comment by agentzh** [comment]
@lixiaominggit Please do not use Chinese here. This place is considered English only. If you really want to use Chinese, please join and post to the openresty (Chinese) mailing list instead. Please see http://openresty.org/en/community.html Thanks for your cooperation.

Regarding your question, it's really about nginx basics, not about this module. Please see

http://nginx.org/en/docs/http/ngx_http_core_module.html#default_type

**Comment by lixiaominggit** [comment]
ok thanks
