### ISSUE TITLE
no redis2 query specified or the query is empty

### ISSUE THREAD

**Issue by dipenpatel235** [openresty/redis2-nginx-module#43]
**## Get Below Error with nginx so please help to fix that**

2016/11/27 03:50:30 [error] 7294#0: *66 no redis2 query specified or the query is empty, client: 150.107.101.46, server: localhost, request: "GET / HTTP/1.1", subrequest: "/redis_get", host: "localhost", referrer: "https://localhost/admin"
2016/11/27 03:50:30 [error] 7294#0: *66 no redis2 query specified or the query is empty, client: 150.107.101.46, server: localhost, request: "GET /activity HTTP/1.1", subrequest: "/redis_get", host: "localhost", referrer: "https://localhost/admin"
2016/11/27 03:50:36 [error] 7294#0: *75 no redis2 query specified or the query is empty, client: 150.107.101.46, server: localhost, request: "GET /blog/all HTTP/1.1", subrequest: "/redis_get", host: "localhost", referrer: "https://localhost/activity"
2016/11/27 03:50:36 [error] 7294#0: *75 no redis2 query specified or the query is empty, client: 150.107.101.46, server: localhost, request: "GET /bookmarks/all HTTP/1.1", subrequest: "/redis_get", host: "localhost", referrer: "https://localhost/activity"
2016/11/27 03:50:37 [error] 7294#0: *72 no redis2 query specified or the query is empty, client: 150.107.101.46, server: localhost, request: "GET /file/all HTTP/1.1", subrequest: "/redis_get", host: "localhost", referrer: "https://localhost/activity"
2016/11/27 03:50:42 [error] 7294#0: *82 no redis2 query specified or the query is empty, client: 150.107.101.46, server: localhost, request: "GET /groups/all HTTP/1.1", subrequest: "/redis_get", host: "localhost", referrer: "https://localhost/activity"

## 
**Nginx version and conf file info:**

 **./nginx  -V**
nginx version: openresty/1.11.2.2
built by gcc 4.8.2 20131212 (Red Hat 4.8.2-8) (GCC)
built with OpenSSL 1.0.1e-fips 11 Feb 2013
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt=-O2 --add-module=../ngx_devel_kit-0.3.0 --add-module=../echo-nginx-module-0.60 --add-module=../xss-nginx-module-0.05 --add-module=../ngx_coolkit-0.2rc3 --add-module=../set-misc-nginx-module-0.31 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.06 --add-module=../srcache-nginx-module-0.31 --add-module=../ngx_lua-0.10.7 --add-module=../ngx_lua_upstream-0.06 --add-module=../headers-more-nginx-module-0.32 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.17 --add-module=../redis2-nginx-module-0.13 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.14 --add-module=../rds-csv-nginx-module-0.07 --with-ld-opt=-Wl,-rpath,/usr/local/openresty/luajit/lib --with-http_ssl_module

# _**see mine attached nginc.conf file **_ 
[nginx_redis_cache.txt](https://github.com/openresty/redis2-nginx-module/files/614416/nginx_redis_cache.txt)

**Comment by agentzh** [comment]
@dipenpatel235 You made a mistake by using `redis2_pass`  instead of `redis_pass` in your `/redis_get` location. Read the corresponding documentation more carefully:

https://github.com/openresty/srcache-nginx-module#caching-with-redis

**Comment by dipenpatel235** [comment]
thanks...
now that error is fixed.
