### ISSUE TITLE
in redis not store Keys of all URL

### ISSUE THREAD

**Issue by dipenpatel235** [openresty/redis2-nginx-module#44]
Please help me to fix store redis key in redis 
X-Cached-From:	MISS   for all after hit url many times

because it is trying to get that key but that key is not seen in redis db

[root@dipen conf]# redis-cli monitor
1480268347.871964 "select" "0"
1480268347.871980 "get" "c40932017eaa71e8eb07236f7a351d49"
1480268351.175680 "ttl" "c40932017eaa71e8eb07236f7a351d49"
1480268352.208962 "select" "0"
1480268352.208978 "get" "316e2b0423dd1b6fbce5051b43b36a94"
1480268352.947172 "ttl" "316e2b0423dd1b6fbce5051b43b36a94"

[root@dipen conf]# redis-cli
redis 127.0.0.1:6379> KEYS *
(empty list or set)
redis 127.0.0.1:6379>

**## Nginx.conf File** 
[nginx_redis_cache.txt](https://github.com/openresty/redis2-nginx-module/files/614854/nginx_redis_cache.txt)

**Comment by agentzh** [comment]
@dipenpatel235 You're using the MD5 checksum of the keys.
