### ISSUE TITLE
fallback to file on connectivity error

### ISSUE THREAD

**Issue by nitzanav** [openresty/redis2-nginx-module#45]
when there is connectivity error to redis? how can we not fail the nginx request and output some error log?

**Comment by agentzh** [comment]
@nitzanav What you are saying is not true. Just check out our existing test cases on various different kinds of connectivity errors and error log messages.

**Comment by nitzanav** [comment]
10x. i am on it.

**Comment by nitzanav** [comment]
closing this issue till I investigate what you described :)
