### ISSUE TITLE
“OOM command not allowed” response on redis2_pass should alert to nginx error.log

### ISSUE THREAD

**Issue by Blasterdick** [openresty/redis2-nginx-module#50]
While using `redis2_pass` and `redis2_query` in openresty location config, I can't get an error message in nginx logs in the situation, when redis.conf has those lines:

    maxmemory 1073741824
    maxmemory-policy noeviction

If the limit of used RAM by the redis instance was reached, redis start to reply with "OOM command not allowed" error to the `push` command.

Why didn't nginx print error message while it can't push data to redis cause of OOM on it?

**Comment by agentzh** [comment]
@Blasterdick This module simply forwards the error as the response body. Well, if you need finer control over redis communications, you should use the ngx_lua module and the lua-resty-redis module (or even better, just use OpenResty).

**Comment by Blasterdick** [comment]
@agentzh AFAIK I can't use nginx default `upstream {}` functionality with `red:connect()`. If I'm right, what alternative to this should I use with `lua-resry-redis`? Thanks in advance.
