### ISSUE TITLE
QUESTION: Can I use redis return to identify my upstream?

### ISSUE THREAD

**Issue by vctrferreira** [openresty/redis2-nginx-module#52]
So, I want use this module to consult in redis which server I will redirect for specific KEY, like this

My servers list in redis (this will be dynamic list):
(key -> value)

```
key1 -> 127.0.0.1
key2 -> 127.0.0.2
```

Request received in NGINX:

> /get?key=key1

Nginx redirect my request to 127.0.0.1

with this module I can do it?

**Comment by agentzh** [comment]
@vctrferreira You should use the `ngx_lua` module and `lua-resty-redis` library for such things (or even better, just use OpenResty).
