### ISSUE TITLE
nginx proxy_cache with redis_pass

### ISSUE THREAD

**Issue by Himanshu4** [openresty/redis2-nginx-module#54]
Hi agentzh,

I am using redis2 module for connecting openresty with redis. I want to avoid roundtrip time b/w servers and redis by caching the redis response on the local disk for a very small amount of time.

Here is my standalone example:

#Proxy cache
proxy_cache_path        cache keys_zone=rediscache:5m max_size=20m;

location /redis_get {
	    internal;
	    proxy_pass_request_headers off;
      	    set_unescape_uri $key $arg_key;  # this requires ngx_set_misc
            redis2_query get $key;
            redis2_pass $redis_slave;
            proxy_ignore_headers Cache-Control;
            proxy_temp_path         cache/tmp;
            proxy_cache_use_stale   updating;
            proxy_cache_lock on;
            proxy_cache_valid any 30m;
            proxy_cache  rediscache;
    	}

But this is not caching the response on the disk. The local disk does not contain any files. Also, when I run MONITOR on redis, I can see the commands getting sent on the redis.

Any help would be appreciated.

**Comment by agentzh** [comment]
@Himanshu4 You cannot use `proxy_pass` and `redis2_pass` in the same location since only one can win.

**Comment by agentzh** [comment]
@Himanshu4 You may want to check out the `ngx_srcache` module:

https://github.com/openresty/srcache-nginx-module

**Comment by Himanshu4** [comment]
I have given a look at the `ngx_srcache` module. I think it caches the response in redis/memcached. I guess you have not understood my requirement. I want to cache the redis response returned from `redis2` module on the local disk so that network round trip is saved. 
Is there a way to do it?

**Comment by agentzh** [comment]
@Himanshu4 You can use lua-resty-redis library and do ANY special processing with Lua via OpenResty's `ngx_lua` module (it's recommended to use OpenResty directly).
